import React from 'react'
import { Navigate } from 'react-router-dom'
import { useAuth } from './AuthContext'

// Whole component generated by ChatGPT 4o

const PublicRoute = ({ children }) => {
  const { user, loading } = useAuth();

  if (loading) return <p>Loading...</p>;
  return !user ? children : <Navigate to="/dashboard" />;
};