//Whole thing generated by Claude AI

export const getEmbedUrl = (url) => {
    if (!url) return '';
    
    // If it's already an embed URL, return as is
    if (url.includes('/embed')) return url;
    
    // Convert regular Google Maps URL to embed URL
    if (url.includes('google.com/maps')) {
        // Extract coordinates or place info
        try {
            // For URLs with coordinates like: https://maps.google.com/?q=lat,lng
            if (url.includes('q=')) {
                const urlParams = new URLSearchParams(url.split('?')[1]);
                const query = urlParams.get('q');
                return `https://www.google.com/maps/embed/v1/place?key=AIzaSyBFw0Qbyq9zTFTd-tUY6dw901SwHSRnpys&q=${encodeURIComponent(query)}`;
            }
            
            // For URLs with @ coordinates
            if (url.includes('@')) {
                const coords = url.split('@')[1].split(',');
                return `https://www.google.com/maps/embed/v1/view?key=AIzaSyBFw0Qbyq9zTFTd-tUY6dw901SwHSRnpys&center=${coords[0]},${coords[1]}&zoom=15`;
            }
            
            // Simple fallback - try adding embed
            return url.replace('google.com/maps', 'google.com/maps/embed');
        } catch {
            return '';
        }
    }
    
    return url;
};